export const INFO_REQUEST = 'INFO_REQUEST';
export const INFO_SUCCESS = 'INFO_SUCCESS';
export const INFO_FAIL = 'INFO_FAIL';
export const VACANCY_REQUEST = 'VACANCY_REQUEST';
export const VACANCY_SUCCESS = 'VACANCY_SUCCESS';
export const VACANCY_FAIL = 'VACANCY_FAIL';